VirtualWallet/urls.py
from django.contrib import admin
from django.conf.urls import url,include,handler404

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wallet/', include('wallet.urls',namespace='wallet')),
    url(r'^', include('wallet.urls')),
     url(r'^user/password/reset/$',
        'django.contrib.auth.views.password_reset',
        {'post_reset_redirect' : '/user/password/reset/done/'},
        name="password_reset"),
    url(r'^user/password/reset/done/$',
        'django.contrib.auth.views.password_reset_done'),
    url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^reset/done/$', 'wallet.views.login_user', name='password_reset_complete'),
]

wallet/urls.py
from django.conf.urls import url,handler404
from . import views
from django.conf.urls import patterns, url

app_name = 'wallet'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login_user$', views.login_user, name='login_user'),
    url(r'^register_user$', views.register_user, name='register_user'),
    url(r'^add_user_details/$', views.add_user_details, name='add_user_details'),
    url(r'^recharge$', views.recharge, name='recharge'),
    url(r'^my_wallet$', views.my_wallet, name='my_wallet'),
    url(r'^add_debit$', views.add_debit, name='add_debit'),
    url(r'^logout_user$', views.logout_user, name='logout_user'),
    url(r'^add_balance$', views.add_balance, name='add_balance'),
    url(r'^all_orders$', views.all_orders, name='all_orders'),
    url(r'^transfer_balance$', views.transfer_balance, name='transfer_balance'),
    url(r'^aboutus$', views.aboutus, name='aboutus'),
    url(r'^contactus$', views.contactus, name='contactus'),
    url(r'^termsandconditions$', views.termsandconditions, name='termsandconditions'),
    url(r'^developers$', views.developers, name='developers'),
    url(r'^account_verify$', views.account_verify, name='account_verify'),
    # url(r'^user/password/reset/$',
    #     'django.contrib.auth.views.password_reset',
    #     {'post_reset_redirect' : '/user/password/reset/done/'},
    #     name="password_reset"),
    # url(r'^user/password/reset/done/$',
    #     'django.contrib.auth.views.password_reset_done'),
    # url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    #
    #
    # url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
]

wallet/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Owner, Recharge, Debit, Balance, Transfer,CodeReceived
from django.core.validators import RegexValidator


class UserReg(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, validators=[RegexValidator(regex=r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&]{8,20}', message="Password should contain Minimum 8 characters, at least 1 Uppercase Alphabet, 1 Lowercase Alphabet, 1 Number and 1 Special Character")])
    username = forms.CharField(min_length=5)
    email = forms.EmailField(required=True)

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("This email is already registered with us")
        return data

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class OwnerInfo(forms.ModelForm):

    class Meta:
        model = Owner
        fields = ['first_name', 'last_name', 'phone_number']


class RechargeForm(forms.ModelForm):

    class Meta:
        model = Recharge
        fields = ['phone_number', 'type', 'operator', 'circle', 'plan']


class AddDebit(forms.ModelForm):

    class Meta:
        model = Debit
        fields = ['debitNumber', 'expiration', 'cvv']


class AddBalance(forms.ModelForm):

    class Meta:
        model = Balance
        fields = ['amount']


class TransferBalance(forms.ModelForm):

    class Meta:
        model = Transfer
        fields = ['phone_number', 'transfer_amount']


class CodeVerification(forms.ModelForm):

    class Meta:
        model = CodeReceived
        fields = ['verification_code']

wallet/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import render,render_to_response,RequestContext
from .forms import OwnerInfo, UserReg,RechargeForm,AddDebit,AddBalance,TransferBalance,CodeVerification
from .models import Owner, Debit ,Recharge ,Transfer,User,ReceivedAmount,CodeSent,CodeReceived
from django.db.models import F
from django.core.mail import send_mail
from django.http import HttpResponse
import random
import string


def ConfirmationAccountMail(request,emailto,usrname,passwrd):
    allowed_chars = ''.join((string.ascii_lowercase, string.ascii_uppercase, string.digits))
    unique_id = ''.join(random.choice(allowed_chars) for _ in range(32))
    code = CodeSent.objects.filter(user = request.user).create(sent_code = unique_id)
    code.user=request.user
    code.save()
    content = 'Hello, '+usrname + '\nThanks For Signing Up On Virtual Wallet\nUsername :' +usrname+'\nVerification Code: '+unique_id+'\n\nAbout Virtual Wallet:\n\n'+'Virtual wallet is a web platform or system where user will be able to maintain his wallet\nand he will be able to use his wallet money to recharge his mobile and can\neven transfer funds/wallet balance to other users.\nYou will also be able to add money to wallet through debit card.\n\nWe hope everything goes well, and once again, if you need help, please dont hesitate to get in touch.\n\nContact us: care@virtualwallet.com\n\nRoom No: 605,TE COMPS\nSardar Patel Institute Of Technology\nAndheri West, Mumbai - 4000 05'
    send_mail("Welcome To Virtual Wallet!",content, "virtual_wallet@hotmail.com", [emailto])


def index(request):
    return render_to_response('wallet/index.html', locals(), context_instance=RequestContext(request))


def developers(request):
    return render_to_response('wallet/developers.html', locals(), context_instance=RequestContext(request))


def aboutus(request):
    return render_to_response('wallet/about_us.html', locals(), context_instance=RequestContext(request))


def contactus(request):
    return render_to_response('wallet/contact_us.html', locals(), context_instance=RequestContext(request))


def termsandconditions(request):
    return render_to_response('wallet/tc.html', locals(), context_instance=RequestContext(request))


def login_user(request):
    if not request.user.is_authenticated():
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    owners = Owner.objects.filter(user=request.user)
                    debits = Debit.objects.filter(user=request.user)
                    code_rec = CodeReceived.objects.filter(user=request.user)
                    return render(request, 'wallet/home_user.html', {'owners': owners, 'debits': debits,'code_rec':code_rec})
                else:
                    return render(request, 'wallet/login_user.html', {'error_message': 'Your account has been disabled'})
            else:
                return render(request, 'wallet/login_user.html', {'error_message': 'Invalid login'})
        return render(request, 'wallet/login_user.html')
    else:
        return render(request, 'wallet/index.html')


def register_user(request):
    form = UserReg(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        email = form.cleaned_data['email']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                owners = Owner.objects.filter(user=request.user)
                ConfirmationAccountMail(request,email,username,password)
                return render(request, 'wallet/my_wallet.html', {'owners': owners})
    context = {
        "form": form,
    }
    return render(request, 'wallet/register_user.html', context)


def add_user_details(request):
    if not request.user.is_authenticated():
        return render(request, 'wallet/login_user.html')
    else:
        code_rec = CodeReceived.objects.filter(user=request.user)
        owners = Owner.objects.filter(user=request.user)
        form = OwnerInfo(request.POST or None)
        if form.is_valid():
            owner = form.save(commit=False)
            owner.user = request.user
            owner.save()
            return render(request, 'wallet/my_wallet.html', {'owner': owner, 'owners': owners,'code_rec':code_rec})
        context = {
            "form": form,
            'code_rec':code_rec,
        }
        return render(request, 'wallet/add_user_details.html', context)


def recharge(request):
    if not request.user.is_authenticated():
        return render(request, 'wallet/login_user.html')
    else:
        code_rec = CodeReceived.objects.filter(user=request.user)
        owners = Owner.objects.filter(user=request.user)
        debits = Debit.objects.filter(user=request.user)
        user=request.user
        emailid=user.email
        recNum = Recharge.objects.filter(user=request.user).__len__() + 1
        form = RechargeForm(request.POST or None)
        for owner in owners:
            bal = owner.balance
            fname=owner.first_name
        if form.is_valid():
            owner = form.save(commit=False)
            plan = form.cleaned_data['plan']
            mob = form.cleaned_data['phone_number']
            if plan > bal:
                return render(request, 'wallet/recharge_unsuccessful.html',{'debits':debits})
            elif recNum % 5 == 0:
                Owner.objects.filter(id__in=owners).update(balance=F('balance') + 20)
                Owner.objects.filter(id__in=owners).update(balance=F('balance') - plan)
                owner.user = request.user
                owner.save()
                send_mail("Recharge Confirmation!",'Hello, '+fname+'\nRecharge of Rs.'+str(plan)+' was successful on mobile number '+mob+'\nUpdated Wallet Balance :Rs.'+str(bal-plan+20)+'\n\n\nContact us: care@virtualwallet.com\n\nRoom No: 605,TE COMPS\nSardar Patel Institute Of Technology\nAndheri West, Mumbai - 4000 058', "virtual_wallet@hotmail.com", [emailid])
                send_mail("You Received Cashback Of Rs.20",'Hello, '+fname+'\nRs.'+str(20)+' added to your wallet\nRecharge 5 More Times To Get Another Cashback Of Rs.20  \nUpdated Wallet Balance :Rs.'+str(bal-plan+20)+'\n\n\nContact us: care@virtualwallet.com\n\nRoom No: 605,TE COMPS\nSardar Patel Institute Of Technology\nAndheri West, Mumbai - 4000 058', "virtual_wallet@hotmail.com", [emailid])
                return render(request, 'wallet/cashback.html', {'owner': owner, 'owners': owners, 'plan':plan, 'mob': mob})
            else:
                Owner.objects.filter(id__in=owners).update(balance=F('balance') - plan)
                owner.user = request.user
                owner.save()
            send_mail("Recharge Confirmation!",'Hello, '+fname+'\nRecharge of Rs.'+str(plan)+' was successful on mobile number '+mob+'\nUpdated Wallet Balance :Rs.'+str(bal-plan)+'\n\n\nContact us: care@virtualwallet.com\n\nRoom No: 605,TE COMPS\nSardar Patel Institute Of Technology\nAndheri West, Mumbai - 4000 058', "virtual_wallet@hotmail.com", [emailid])
            return render(request, 'wallet/recharge_successful.html', {'owner': owner, 'owners': owners, 'plan':plan, 'mob': mob})
        context = {
            "form": form,
            'owners':owners,
            'code_rec':code_rec
        }
        return render(request, 'wallet/recharge.html', context)


def my_wallet(request):
    if not request.user.is_authenticated():
        return render(request, 'wallet/login_user.html')
    else:
        code_rec = CodeReceived.objects.filter(user=request.user)
        code_sent = CodeSent.objects.get(user = request.user)
        debits = Debit.objects.filter(user=request.user)
        owners = Owner.objects.filter(user=request.user)
        return render(request, 'wallet/my_wallet.html', {'owners': owners,'debits':debits,'code_rec':code_rec,'code_sent':code_sent})


def logout_user(request):
    logout(request)
    return render(request, 'wallet/index.html')


def add_debit(request):
    if not request.user.is_authenticated():
        return render(request, 'wallet/login_user.html')
    else:
        debits = Debit.objects.filter(user=request.user)
        owners = Owner.objects.filter(user=request.user)
        form = AddDebit(request.POST or None)
        if form.is_valid():
            debit = form.save(commit=False)
            debit.user = request.user
            debit.save()
            return render(request, 'wallet/add_debit.html', {'debit': debit, 'debits': debits, 'owners': owners})
        context = {
            "form": form,
            'debits': debits,
            "owners":owners
        }
        return render(request, 'wallet/add_debit.html', context)


def add_balance(request):
    if not request.user.is_authenticated():
        return render(request, 'wallet/login_user.html')
    else:
        code_rec = CodeReceived.objects.filter(user=request.user)
        debits = Debit.objects.filter(user=request.user)
        owners = Owner.objects.filter(user=request.user)
        form = AddBalance(request.POST or None)
        user=request.user
        emailid=user.email
        for owner in owners:
            bal = owner.balance
            fname=owner.first_name
        if form.is_valid():
            balance = form.save(commit=False)
            amt = form.cleaned_data['amount']
            for deb in debits:
                dbal = deb.dbalance
            if dbal >= amt:

wallet/templates/wallet/base_bottom.html
{% load staticfiles %}
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'wallet/style.css' %}">
{% block body %}
<img style="width:100%;" id="image" src="../../static/wallet/images/recharge.png">
<img style="width:100%;" id="image" src="../../static/wallet/images/rechrg.png">
<div class="footer-top">
	<div class="container">
			<div class="col-md-3">
				<h3>MOBILE RECHARGES</h3>
				<ul>
                   <li><a href="{% url "wallet:recharge" %}">Reliance</a></li>
                    <li><a href="{% url "wallet:recharge" %}">Aircel</a></li>
                    <li><a href="{% url "wallet:recharge" %}">Vodafone</a></li>
                   <li><a href="{% url "wallet:recharge" %}">Airtel</li>
                   <li><a href="{% url "wallet:recharge" %}">Docomo</a></li>
                   <li><a href="{% url "wallet:recharge" %}">MTS</a></li>
                   <li><a href="{% url "wallet:recharge" %}">Idea</a></li>
				</ul>
			</div>
			<div class="col-md-3">
				<h3>DTH RECHARGES</h3>
				<ul>
					<li>Airtel Digital TV Recharges</li>
					<li>Dish TV Recharges</li>
					<li>Tata Sky Recharges</li>
					<li>Reliance Digital TV Recharges</li>
					<li>Sun Direct Recharges</li>
					<li>Videocon D2H Recharges</li>
				</ul>
			</div>
			<div class="col-md-3">
				<h3>PAYMENT OPTIONS</h3>
				<ul>
					<li>Credit Cards</li>
					<li>Debit Cards</li>
					<li>Any Visa Debit Card (VBV)</li>
					<li>Direct Bank Debits</li>
					<li>Cash Cards</li>
				</ul>
			</div>
        <div class="col-md-3">
				<h3>VIRTUAL WALLET</h3>
				<ul>
                   <li><a href="{% url "wallet:aboutus" %}">About Us</a></li>
                   <li><a href="{% url "wallet:contactus" %}">Contact Us</a></li>
                   <li><a href="{% url "wallet:termsandconditions" %}">Terms & Conditions</a></li>
                    <li><a href="{% url "wallet:developers" %}">Developers</a></li>

				</ul>
			</div>
		</div>
	</div>

<div class="footer">
	<div class="container">
		<h2><a href="{% url 'wallet:index' %}">Virtual Wallet</a></h2>
		<img src="../../static/wallet/images/logos.png" alt=" " />
		<p>© 2016 Virtual Wallet. All Rights Reserved</p>
	</div>
</div>
{% endblock %}

wallet/templates/wallet/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" id="fields" >{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

wallet/templates/wallet/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Virtual Wallet</title>
  <meta charset="utf-8">
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Amaranth" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'wallet/style.css' %}"/>

  
</head>
<body>
{% if request.user.is_authenticated %}
<ul class='navi'>
   <li class='navig'><a id="hd" href="{% url "wallet:index" %}"><i><img src="../../static/wallet/images/iconlogo.png" alt=" " /></i>VIRTUAL WALLET</a></li>
   <li class='navig'><a id="md" href="{% url "wallet:recharge" %}">RECHARGE</a></li>
   <li class='navig'><a id="md" href="{% url "wallet:my_wallet" %}">MY WALLET</a></li>
   <li class='navig'><a id="md" href="{% url "wallet:transfer_balance" %}">TRANSFER</a></li>
    <li class='navig'><a id="md" href=" {% url 'wallet:all_orders'  %}">TRANSACTIONS</a></li>
    <li class='navig'><a id="md" href="{% url 'wallet:logout_user' %}">LOGOUT</a></li>
   <li class='navig'><a id="md" href="{% url "wallet:my_wallet" %}"><i><img src="../../static/wallet/images/userr.png" alt=" " /></i>&nbsp;&nbsp;{{ user.username.upper }}</a></li>
</ul>

    {% else %}
<ul class='navi'>
   <li class='navig'><a id="hd" href="{% url "wallet:index" %}"><i><img src="../../static/wallet/images/iconlogo.png" alt=" " /></i>VIRTUAL WALLET</a></li>
   <li class='navig'><a id="md" href="{% url "wallet:recharge" %}">RECHARGE</a></li>
   <li class='navig'><a id="md" href="{% url "wallet:my_wallet" %}">MY WALLET</a></li>
   <li class='navig'><a id="md" href="{% url "wallet:transfer_balance" %}">TRANSFER</a></li>
   <li class='navig'><a id="md" href="{% url 'wallet:login_user' %}">LOGIN</a></li>
    <li class='navig'><a id="md" href="{% url 'wallet:register_user' %}">REGISTER</a></li>
        <li class='navig'><a id="md" href="{% url "wallet:my_wallet" %}"><i><img src="../../static/wallet/images/userr.png" alt=" " /></i>&nbsp;&nbsp;{{ user.username.upper }}</a></li>
</ul>
{% endif %}
<div class="imagewrap">
<img style="width:100%; height:600px;-webkit-filter: blur(1px);filter: blur(1.5);" id="image" src="../../static/wallet/images/bg.png">
<h2 id="tagline">Get Free Coupons and Discounts With Every Recharge</h2>
 <a href="{% url "wallet:recharge" %}" ><input type="button" class="button1" value="RECHARGE" /></a>
 <a href="{% url "wallet:my_wallet" %}" ><input type="button" class="button2" value="WALLET" /></a>
 <a href="{% url "wallet:transfer_balance" %}" ><input type="button" class="button3" value="TRANSFER MONEY" /></a>
</div>
<img style="width:100%;" id="image" src="../../static/wallet/images/rechrg.png">
<img style="width:100%;" id="image" src="../../static/wallet/images/recharge.png">
<img style="width:100%;" id="image" src="../../static/wallet/images/offers.png">

<div class="footer-top">
	<div class="container">
			<div class="col-md-3">
				<h3>MOBILE RECHARGES</h3>
				<ul>
                   <li><a href="{% url "wallet:recharge" %}">Reliance</a></li>
                    <li><a href="{% url "wallet:recharge" %}">Aircel</a></li>
                    <li><a href="{% url "wallet:recharge" %}">Vodafone</a></li>
                   <li><a href="{% url "wallet:recharge" %}">Airtel</li>
                   <li><a href="{% url "wallet:recharge" %}">Docomo</a></li>
                   <li><a href="{% url "wallet:recharge" %}">MTS</a></li>
                   <li><a href="{% url "wallet:recharge" %}">Idea</a></li>
				</ul>
			</div>
			<div class="col-md-3">
				<h3>DTH RECHARGES</h3>
				<ul>
					<li>Airtel Digital TV Recharges</li>
					<li>Dish TV Recharges</li>
					<li>Tata Sky Recharges</li>
					<li>Reliance Digital TV Recharges</li>
					<li>Sun Direct Recharges</li>
					<li>Videocon D2H Recharges</li>
				</ul>
			</div>
			<div class="col-md-3">
				<h3>PAYMENT OPTIONS</h3>
				<ul>
					<li>Credit Cards</li>
					<li>Debit Cards</li>
					<li>Any Visa Debit Card (VBV)</li>
					<li>Direct Bank Debits</li>
					<li>Cash Cards</li>
				</ul>
			</div>
        <div class="col-md-3">
				<h3>VIRTUAL WALLET</h3>
				<ul>
                   <li><a href="{% url "wallet:aboutus" %}">About Us</a></li>
                   <li><a href="{% url "wallet:contactus" %}">Contact Us</a></li>
                   <li><a href="{% url "wallet:termsandconditions" %}">Terms & Conditions</a></li>
                    <li><a href="{% url "wallet:developers" %}">Developers</a></li>

				</ul>
			</div>
		</div>
	</div>	

<div class="footer">
	<div class="container">
		<h2><a href="{% url 'wallet:index' %}">Virtual Wallet</a></h2>
		<img src="../../static/wallet/images/logos.png" alt=" " />
		<p>© 2016 Virtual Wallet. All Rights Reserved</p>
	</div>
</div>
</body>
</html>

wallet/templates/wallet/login_user.html
{% load staticfiles %}
<title>{% block title %}User Login{% endblock %}</title>

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Amaranth" rel="stylesheet">

<link rel="stylesheet" href="{% static 'wallet/style.css' %}">
{% block body %}
    <ul class='navi'>
   <li class='navig'><a id="hd" href="{% url "wallet:index" %}"><i><img src="../../static/wallet/images/iconlogo.png" alt=" " /></i>VIRTUAL WALLET</a></li>
   <li class='navig'><a id="md" href="{% url "wallet:recharge" %}">RECHARGE</a></li>
   <li class='navig'><a id="md" href="{% url "wallet:my_wallet" %}">MY WALLET</a></li>
   <li class='navig'><a id="md" href="{% url "wallet:transfer_balance" %}">TRANSFER</a></li>
           <li class='navig'><a id="md" href="{% url "wallet:register_user" %}">REGISTER</a></li>

    <li class='navig'><a id="md" href="{% url "wallet:my_wallet" %}"><i><img src="../../static/wallet/images/userr.png" alt=" " /></i>&nbsp;&nbsp;{{ user.username.upper }}</a></li>
</ul>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3 id="form">Log In</h3>
                    {% if error_message %}
                        <p><strong class="text-danger">{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'wallet:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" id="fields" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" id="fields" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Login</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Forgot Password? <a href='http://127.0.0.1:8000/user/password/reset/'>Click here</a><br>
                    Don't have an account? <a href="{% url 'wallet:register_user' %}">Click here</a> to register.
                    By Logging in you agree with our <a href="{% url 'wallet:termsandconditions' %}">Terms & Conditions</a>
                </div>
            </div>
        </div>
    <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is Virtual Wallet?</h3>
                    <p>Virtual wallet is a web platform or system where user will be able to
                        maintain his wallet and he will be able to use his wallet money to recharge his
                        mobile and can even transfer funds/wallet balance to other users. User will also be able
                        to add money to wallet through debit card.</p>
                    <h3>How do I Recharge?</h3>
                    <ul>
                        <li>Register/Login to your account.</li>
                        <li>Click on Recharge;</li>
                        <li>Enter the necessary details.</li>
                        <li>Make payment.</li>
                    </ul>
                    <h3>What Do I Transfer Balance To Other User?</h3>
                    <ul>
                        <li>Login to your account.</li>
                        <li>Click on Money Transfer</li>
                        <li>Enter the mobile number(whom you would like to transfer).</li>
                        <li>Enter the amount.</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
    </div>
    {% include 'wallet/base_bottom.html' %}
{% endblock %}

wallet/templates/wallet/menu_base.html
{% load staticfiles %}
<link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Amaranth" rel="stylesheet">
<link rel="stylesheet" href="{% static 'wallet/style.css' %}">
{% block body %}
<ul class='navi'>
   <li class='navig'><a id="hd" href="{% url "wallet:index" %}"><i><img src="../../static/wallet/images/iconlogo.png" alt=" " /></i>VIRTUAL WALLET</a></li>
   <li class='navig'><a id="md" href="{% url "wallet:recharge" %}">RECHARGE</a></li>
   <li class='navig'><a id="md" href="{% url "wallet:my_wallet" %}">MY WALLET</a></li>
   <li class='navig'><a id="md" href="{% url "wallet:transfer_balance" %}">TRANSFER</a></li>
    <li class='navig'><a id="md" href=" {% url 'wallet:all_orders'  %}">TRANSACTIONS</a></li>
    <li class='navig'><a id="md" href="{% url 'wallet:logout_user' %}">LOGOUT</a></li>
    <li class='navig'><a id="md" href="{% url "wallet:my_wallet" %}"><i><img src="../../static/wallet/images/userr.png" alt=" " /></i>&nbsp;&nbsp;{{ user.username.upper }}</a></li>
</ul>
{% endblock %}